<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

        <h2 class="text-center"><?= $this->translate('Sign in'); ?></h2>
        <br>

        <form action="<?= $this->url('login'); ?>" method="post">

            <?php if (!empty($this->error)): ?>
                <div class="alert alert-danger">
                    <strong><?= $this->translate('Wrong email address or password. Try again.'); ?></strong>
                </div>
            <?php endif; ?>

            <div class="form-group">
                <label for="login-email"><?= $this->translate('Email'); ?></label>
                <input class="form-control" type="email" name="email" value="<?= htmlspecialchars($this->email); ?>" id="login-email" />
            </div>
            <div class="form-group">
                <label for="login-password"><?= $this->translate('Password'); ?></label>
                <input class="form-control" type="password" name="password" value="" id="login-password" />
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="remember" value="on" <?= !empty($this->remember) ? 'checked' : ''; ?> />
                    <?= $this->translate('Remember me'); ?>
                </label>
            </div>
            <div class="text-center">
                <button class="btn btn-primary btn-block">
                    <?= $this->translate('Login'); ?>
                </button>
            </div>
        </form>

        <br>
        <div>
            <span class="glyphicon glyphicon-arrow-right"></span>
            <a href="javascript:alert('Not supported yet!');">
                <?= $this->translate('Forgot your password? Reset it'); ?>
            </a>
        </div>
        <div>
            <span class="glyphicon glyphicon-arrow-right"></span>
            <a href="<?= $this->url('register'); ?>">
                <?= $this->translate('New user? Create an account'); ?>
            </a>
        </div>

    </div>
    <div class="col-md-4"></div>
</div>

<script type="text/javascript">
    $(function () {
        var $loginEmail = $('#login-email');
        var $loginPassword = $('#login-password');
        if ($loginEmail.val() == '') {
            $loginEmail.focus();
        } else if ($loginPassword.val() == '') {
            $loginPassword.focus();
        }
    });
</script>