<h1 class="page-header"><?= $this->translate('Report list'); ?></h1>

<form action="<?= $this->url('report-index'); ?>" method="get">
    <div class="row">
        <div class="col-md-2 col-sm-3">
            <div class="form-group">
                <label for="filter-date-from"><?= $this->translate('From date'); ?></label>
                <input type="text" name="from" class="form-control" id="filter-date-from"
                       value="<?= $this->formatDate($this->dateFrom); ?>"/>
            </div>
        </div>
        <div class="col-md-2 col-sm-3">
            <div class="form-group">
                <label for="filter-date-to"><?= $this->translate('To date'); ?></label>
                <input type="text" name="to" class="form-control" id="filter-date-to"
                       value="<?= $this->formatDate($this->dateTo); ?>"/>
            </div>
        </div>
        <div class="col-md-2 col-sm-2">
            <div class="form-group">
                <label for="filter-issue"><?= $this->translate('Issue ID'); ?></label>
                <input type="number" name="issue" class="form-control" id="filter-issue"
                       value="<?= $this->issueId; ?>"/>
            </div>
        </div>
        <div class="col-md-2 col-sm-4">
            <div class="form-group">
                <label for="filter-user"><?= $this->translate('User'); ?></label>
                <select name="user" class="form-control" id="filter-user" data-live-search="true">
                    <option value=""><?= $this->translate('Current user'); ?></option>
                    <option data-divider="true"></option>
                    <?php if (!empty($this->users)): ?>
                        <?php /** @var Reportman\Models\User $user */ ?>
                        <?php foreach ($this->users as $user): ?>
                            <option
                                value="<?= $user->getId(); ?>" <?= $user->getId() == $this->userId ? 'selected' : ''; ?>
                                data-content="<img src='<?= $user->getAvatar(20); ?>' width=20 height=20> <?= htmlspecialchars($user->getName()); ?>">
                                <?= htmlspecialchars($user->getName()); ?>
                            </option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </div>
        </div>
    </div>
</form>

<div>
    <?php $exportUrl = $this->url('report-export', [], ['query' => [
        'from' => $this->dateFrom,
        'to' => $this->dateTo,
        'issue' => $this->issueId,
        'user' => $this->userId,
    ]]); ?>
    <a class="btn btn-primary" href="<?= $exportUrl; ?>">
        <span class="glyphicon glyphicon-save"></span>
        <?= $this->translate('Export to file'); ?>
    </a>
    <a class="btn btn-default"
       href="<?= $this->url('report-index'); ?>"><?= $this->translate('Reset filter'); ?></a>
</div>

<br/>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th><?= $this->translate('Date'); ?></th>
            <th><?= $this->translate('Issue ID'); ?></th>
            <th><?= $this->translate('Issue Text'); ?></th>
            <th><?= $this->translate('Spent Time'); ?></th>
            <th><?= $this->translate('Estimated Time'); ?></th>
            <th><?= $this->translate('Complete'); ?></th>
            <th><?= $this->translate('Actions'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($this->reports)): ?>
            <?php $currentDate = null; ?>
            <?php $reportCount = 0; ?>
            <?php /** @var Reportman\Models\Report $report */ ?>
            <?php foreach ($this->reports as $report): ?>
                <?php if ($currentDate != $report->getDate()): ?>
                    <tr>
                        <td>
                            <strong><?= $report->getDateAsDateTime()->format('d. m. Y'); ?></strong>
                        </td>
                        <td colspan="6">&nbsp;</td>
                    </tr>
                    <?php $currentDate = $report->getDate(); ?>
                <?php endif; ?>
                <tr>
                    <td>&nbsp;</td>
                    <td><?= $report->getIssueId(); ?></td>
                    <td><?= htmlspecialchars($report->getIssueText()); ?></td>
                    <td><?= $this->formatTime($report->getSpentTime()); ?></td>
                    <td><?= $this->formatTime($report->getEstimatedTime()); ?></td>
                    <td>
                        <div class="progress" style="margin: 0;" title="<?= $report->getComplete(); ?>%">
                            <div class="progress-bar progress-bar-success progress-striped"
                                 style="width: <?= $report->getComplete(); ?>%;"></div>
                        </div>
                    </td>
                    <td>
                        <button class="btn btn-xs btn-success" onclick="alert('Not implemented yet');">
                            <span class="glyphicon glyphicon-edit"></span>
                            <?= $this->translate('Edit'); ?>
                        </button>
                    </td>
                </tr>
                <?php $reportCount++; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
    <?php if ($reportCount == 0): ?>
        <tfoot>
            <tr>
                <td colspan="7">
                    <?= $this->translate('No records available for current filter.'); ?>
                </td>
            </tr>
        </tfoot>
    <?php endif; ?>
</table>