<h1 class="page-header"><?= $this->translate('Report list'); ?></h1>

<form action="<?= $this->url('report-index'); ?>" method="get">
    <div class="row">
        <div class="col-md-2 col-sm-3">
            <div class="form-group">
                <label for="filter-date-from"><?= $this->translate('From date'); ?></label>
                <input type="text" name="from" class="form-control" id="filter-date-from"
                       value="<?= $this->formatDate($this->dateFrom); ?>"/>
            </div>
        </div>
        <div class="col-md-2 col-sm-3">
            <div class="form-group">
                <label for="filter-date-to"><?= $this->translate('To date'); ?></label>
                <input type="text" name="to" class="form-control" id="filter-date-to"
                       value="<?= $this->formatDate($this->dateTo); ?>"/>
            </div>
        </div>
        <div class="col-md-2 col-sm-2">
            <div class="form-group">
                <label for="filter-issue"><?= $this->translate('Issue ID'); ?></label>
                <input type="number" name="issue" class="form-control" id="filter-issue"
                       value="<?= $this->issueId; ?>"/>
            </div>
        </div>
        <?php if (!empty($this->users)): ?>
            <div class="col-md-3 col-sm-4">
                <div class="form-group">
                    <label for="filter-user"><?= $this->translate('User'); ?></label>
                    <select name="user" class="form-control" id="filter-user" data-live-search="true">
                        <?php /** @var Reportman\Models\User $user */ ?>
                        <?php foreach ($this->users as $user): ?>
                            <option
                                value="<?= $user->getId(); ?>" <?= $user->getId() == $this->userId ? 'selected' : ''; ?>
                                data-content="<img src='<?= $user->getAvatar(20); ?>' class='user-avatar' width=20 height=20> <?= htmlspecialchars($user->getName()); ?>">
                                <?= htmlspecialchars($user->getName()); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>
    </div>
</form>

<div>
    <?php $exportUrl = $this->url('report-export', [], ['query' => [
        'from' => $this->formatDate($this->dateFrom),
        'to' => $this->formatDate($this->dateTo),
        'issue' => $this->issueId,
        'user' => $this->userId,
    ]]); ?>
    <a class="btn btn-primary" href="<?= $exportUrl; ?>">
        <span class="glyphicon glyphicon-save"></span>
        <?= $this->translate('Export to file'); ?>
    </a>
    <a class="btn btn-default"
       href="<?= $this->url('report-index'); ?>"><?= $this->translate('Reset filter'); ?></a>
</div>

<br/>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>
                <?= $this->translate('Date'); ?> &nbsp;
                <?php if ($this->order == 'desc'): ?>
                    <?php $orderUrl = $this->url('report-index', [], ['query' => [
                        'from' => $this->formatDate($this->dateFrom),
                        'to' => $this->formatDate($this->dateTo),
                        'issue' => $this->issueId,
                        'user' => $this->userId,
                        'order' => 'asc'
                    ]]); ?>
                    <a href="<?= $orderUrl; ?>"><span class="glyphicon glyphicon-sort-by-attributes"></span></a>
                <?php else: ?>
                    <?php $orderUrl = $this->url('report-index', [], ['query' => [
                        'from' => $this->formatDate($this->dateFrom),
                        'to' => $this->formatDate($this->dateTo),
                        'issue' => $this->issueId,
                        'user' => $this->userId,
                        'order' => 'desc'
                    ]]); ?>
                    <a href="<?= $orderUrl; ?>"><span class="glyphicon glyphicon-sort-by-attributes-alt"></span></a>
                <?php endif; ?>
            </th>
            <th><?= $this->translate('Issue ID'); ?></th>
            <th><?= $this->translate('Issue Text'); ?></th>
            <th><?= $this->translate('Spent Time'); ?></th>
            <th><?= $this->translate('Estimated Time'); ?></th>
            <th><?= $this->translate('Complete'); ?></th>
            <th><?= $this->translate('Actions'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($this->reports)): ?>
            <?php $currentDate = null; ?>
            <?php $reportCount = 0; ?>
            <?php /** @var Reportman\Models\Report $report */ ?>
            <?php foreach ($this->reports as $report): ?>
                <?php if ($currentDate != $report->getDate()): ?>
                    <tr>
                        <td>
                            <strong><?= $report->getDateAsDateTime()->format('d. m. Y'); ?></strong>
                        </td>
                        <td colspan="6">&nbsp;</td>
                    </tr>
                    <?php $currentDate = $report->getDate(); ?>
                <?php endif; ?>
                <tr>
                    <td>&nbsp;</td>
                    <td><?= $report->getIssueId(); ?></td>
                    <td><?= htmlspecialchars($report->getIssueText()); ?></td>
                    <td><?= $this->formatTime($report->getSpentTime()); ?></td>
                    <td><?= $this->formatTime($report->getEstimatedTime()); ?></td>
                    <td>
                        <div class="progress" style="margin: 0;" title="<?= $report->getComplete(); ?>%">
                            <div class="progress-bar progress-bar-success progress-striped"
                                 style="width: <?= $report->getComplete(); ?>%;"></div>
                        </div>
                    </td>
                    <td>
                        <button class="btn btn-xs btn-success" onclick="ReportDialog.edit(<?= $report->getId(); ?>);"
                            <?= $this->currentUser->getId() != $report->getUserId() ? 'disabled' : ''; ?>>
                            <span class="glyphicon glyphicon-edit"></span>
                            <?= $this->translate('Edit'); ?>
                        </button>
                        <button class="btn btn-xs btn-danger" onclick="reportDelete(<?= $report->getId(); ?>);"
                            <?= $this->currentUser->getId() != $report->getUserId() ? 'disabled' : ''; ?>>
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </td>
                </tr>
                <?php $reportCount++; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
    <?php if ($reportCount == 0): ?>
        <tfoot>
            <tr>
                <td colspan="7">
                    <?= $this->translate('No records available for current filter.'); ?>
                </td>
            </tr>
        </tfoot>
    <?php endif; ?>
</table>


<div class="modal" id="report-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal">
                    <span class="glyphicon glyphicon-remove"></span>
                </button>
                <h4><?= $this->translate('Create/Update report'); ?></h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="report-modal-id" />

                <div class="row">

                    <div class="col-sm-5">
                        <div class="form-group">
                            <label for="report-modal-date"><?= $this->translate('Date'); ?></label>
                            <input type="text" class="form-control" id="report-modal-date"/>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="report-modal-issue-id"><?= $this->translate('Issue ID'); ?></label>
                            <input type="number" class="form-control" min="0" step="1" id="report-modal-issue-id"/>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="report-modal-complete"><?= $this->translate('Complete %'); ?></label>
                            <input type="number" class="form-control" min="0" max="100" step="10"
                                   id="report-modal-complete"/>
                        </div>
                    </div>

                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="report-modal-issue-text"><?= $this->translate('Issue Text'); ?></label>
                            <textarea class="form-control" id="report-modal-issue-text" rows="3"
                                      style="max-width: 100%; min-width: 100%;"></textarea>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="col-sm-6">
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="report-modal-spent-time"><?= $this->translate('Spent time'); ?></label>

                                    <div class="input-group">
                                        <input class="form-control" type="number" min="0" step="1"
                                               id="report-modal-spent-time"/>

                                        <div class="input-group-addon">h</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="report-modal-spent-time-min">&nbsp;</label>

                                    <div class="input-group">
                                        <input class="form-control" type="number" min="0" max="59" step="5"
                                               id="report-modal-spent-time-min"/>

                                        <div class="input-group-addon">m</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label
                                        for="report-modal-estimated-time"><?= $this->translate('Estimated time'); ?></label>

                                    <div class="input-group">
                                        <input class="form-control" type="number" min="0" step="1"
                                               id="report-modal-estimated-time"/>

                                        <div class="input-group-addon">h</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="report-modal-estimated-time-min">&nbsp;</label>

                                    <div class="input-group">
                                        <input class="form-control" type="number" min="0" max="59" step="5"
                                               id="report-modal-estimated-time-min"/>

                                        <div class="input-group-addon">m</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <div class="pull-left">
                    <div id="report-modal-loading" class="text-primary hide">
                        <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> &nbsp;
                        <?= $this->translate('Saving changes ... please wait'); ?>
                    </div>
                    <div id="report-modal-success" class="text-success hide">
                        <span class="glyphicon glyphicon-ok"></span> &nbsp;
                        <?= $this->translate('Changes has saved'); ?>
                    </div>
                </div>
                <div class="pull-right">
                    <button class="btn btn-default" data-dismiss="modal">
                        <?= $this->translate('Cancel'); ?>
                    </button>
                    <button class="btn btn-primary" onclick="ReportDialog.save();">
                        <?= $this->translate('Save changes'); ?>
                    </button>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>