<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <?= $this->headLink()
            ->appendStylesheet($this->basePath('css/bootstrap.css'))
            ->appendStylesheet($this->basePath('css/bootstrap-datepicker.css'))
            ->appendStylesheet($this->basePath('css/bootstrap-select.css'))
            ->appendStylesheet($this->basePath('css/reportman.css'));
        ?>
        <?= $this->headScript()
            ->appendFile($this->basePath('js/jquery.js'))
            ->appendFile($this->basePath('js/bootstrap.js'))
            ->appendFile($this->basePath('js/bootstrap-datepicker.js'))
            ->appendFile($this->basePath('js/bootstrap-select.js'))
            ->appendFile($this->basePath('js/reportman.js'));
        ?>
    </head>
    <body>

        <div class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->url('home'); ?>">
                        <span class="glyphicon glyphicon-list-alt"></span>
                        <?= $this->translate('Reportman'); ?>
                    </a>
                </div>
                <?php if (!empty($this->currentUser)): ?>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="javascript:ReportDialog.create();">
                            <span class="glyphicon glyphicon-plus"></span>
                            <?= $this->translate('New report'); ?>
                        </a>
                    </li>
                </ul>
                <?php endif; ?>
                <?php if (!empty($this->currentUser)): ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="javascript:UserSettings.show();">
                                <img src="<?= $this->currentUser->getAvatar(20); ?>" width="20" height="20" class="user-avatar" />
                                <?= htmlspecialchars($this->currentUser->getName()); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('logout'); ?>">
                                <span class="glyphicon glyphicon-log-out"></span>
                                <?= $this->translate('Logout'); ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>

        <div class="container">
            <?= $this->content; ?>
        </div>

        <?php if (!empty($this->currentUser)): ?>
            <div class="modal" id="user-settings">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button class="close" data-dismiss="modal">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            <h4>User settings</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="user-settings-name"><?= $this->translate('Name'); ?></label>
                                <input type="text" class="form-control" id="user-settings-name" value="<?= htmlspecialchars($this->currentUser->getName()); ?>" />
                            </div>
                            <div class="form-group">
                                <label for="user-settings-email"><?= $this->translate('Email'); ?></label>
                                <input type="email" class="form-control" id="user-settings-email" value="<?= htmlspecialchars($this->currentUser->getEmail()); ?>" />
                            </div>
                            <div class="form-group">
                                <label for="user-settings-password-new"><?= $this->translate('New password'); ?></label>
                                <input type="password" class="form-control" id="user-settings-password-new" />
                                <div class="help-block">
                                    <?= $this->translate('Leave blank if you don\'t want to change your password.'); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="user-settings-password-retype"><?= $this->translate('Retype new password'); ?></label>
                                <input type="password" class="form-control" id="user-settings-password-retype" />
                            </div>
                            <hr />
                            <div class="form-group">
                                <label for="user-settings-password"><?= $this->translate('Current password'); ?></label>
                                <input type="password" class="form-control" id="user-settings-password" />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-default" data-dismiss="modal">
                                <?= $this->translate('Cancel'); ?>
                            </button>
                            <button class="btn btn-primary" onclick="UserSettings.save();">
                                <?= $this->translate('Save changes'); ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    </body>
</html>