<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <?= $this->headLink()
            ->appendStylesheet($this->basePath('css/bootstrap.css'))
            ->appendStylesheet($this->basePath('css/reportman.css'));
        ?>
        <?= $this->headScript()
            ->appendFile($this->basePath('js/jquery.js'))
            ->appendFile($this->basePath('js/bootstrap.js'))
            ->appendFile($this->basePath('js/reportman.js'));
        ?>
    </head>
    <body>

        <div class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->url('home'); ?>">
                        <span class="glyphicon glyphicon-list-alt"></span>
                        <?= $this->translate('Reportman'); ?>
                    </a>
                </div>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="javascript:alert('Not implemented yet');">
                            <span class="glyphicon glyphicon-plus"></span>
                            <?= $this->translate('New report'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?= $this->url('report-index'); ?>">
                            <span class="glyphicon glyphicon-list"></span>
                            <?= $this->translate('Reports'); ?>
                        </a>
                    </li>
                </ul>
                <?php if (!empty($this->currentUser)): ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#">
                                <img src="<?= $this->currentUser->getAvatar(20); ?>" width="20" height="20" class="navbar-avatar" />
                                <?= htmlspecialchars($this->currentUser->getName()); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('logout'); ?>">
                                <span class="glyphicon glyphicon-log-out"></span>
                                <?= $this->translate('Logout'); ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>

        <div class="container">
            <?= $this->content; ?>
        </div>

    </body>
</html>